- name: Deploy
  hosts: all
  tasks:
  - name: Install nginx
    dnf:
      name: nginx
      state: present
  - name: Start nginx
    systemd_service:
      name: nginx
      state: started
      enabled: yes
  - name: Create directory
    file:
      state: directory
      path: /usr/share/nginx/epptec
  - name: Copy files
    copy:
      src: "{{ playbook_dir }}/../build"
      dest: /usr/share/nginx/epptec
  - name: Copy nginx config
    copy:
      src: "{{ playbook_dir }}/nginx.conf"
      dest: /etc/nginx/conf.d/epptec-react-demo.conf
      force: false
  - name: Reload nginx
    systemd_service:
      name: nginx
      state: reloaded

